steps:
  - uses: actions/checkout@v2
  - uses: vitorgus/setup-godot@v1
    with:
      godot-version: 4.2.2
  - name: Web Build
    run: |
      mkdir -v -p build/web
      godot -v --export "HTML5" ./build/web/index.html
  - uses: actions/upload-artifact@v2
    with:
      name: web
      path: build/web
