name: "Build iOS app"

on: [push]

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          xcodebuild archive -project "build/Pokemon Battle-Mode.xcodeproj" -scheme 'Pokemon Battle-Mode' -archivePath Example-Project.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO



          mv Example-Project.xcarchive ${{ runner.temp }}/Example-Project.xcarchive


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: Example-Project
          path: ${{ runner.temp }}/Example-Project.xcarchive
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3
